### ISSUE TITLE
出现了一些错误，请教一下如何解决

### ISSUE THREAD

**Issue by kslr** [ccbikai/backuptoqiniu#3]
错误如下：

Traceback (most recent call last):
  File "./upload.py", line 48, in <module>
    qiniu.io.put_file(uptoken, os.path.basename(localfile), localfile)
  File "/home/backup/qiniu/io.py", line 65, in put_file
    return put(uptoken, key, f, extra)
  File "/home/backup/qiniu/io.py", line 54, in put
    return rpc.Client(conf.UP_HOST).call_with_multipart("/", fields, files)
  File "/home/backup/qiniu/rpc.py", line 59, in call_with_multipart
    return self.call_with(path, mr, content_type, mr.length())
  File "/home/backup/qiniu/rpc.py", line 34, in call_with
    resp = self.round_tripper("POST", path, body)
  File "/home/backup/qiniu/rpc.py", line 17, in round_tripper
    self._conn.request(method, path, body, self._header)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/home/backup/qiniu/httplib_chunk.py", line 84, in _send_request
    self.endheaders(body, is_chunked=is_chunked)
  File "/home/backup/qiniu/httplib_chunk.py", line 100, in endheaders
    self._send_output(message_body, is_chunked=is_chunked)
  File "/home/backup/qiniu/httplib_chunk.py", line 122, in _send_output
    self.send(message_body, is_chunked=is_chunked)
  File "/home/backup/qiniu/httplib_chunk.py", line 40, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe

**Comment by strongme** [comment]
我也是有同样的问题，一直显示在upload但是就是没有反应

**Comment by kslr** [comment]
@strongme 网络问题

**Comment by shibinhu** [comment]
我也是一样的问题，不知道怎么解决，上传那里卡着不动，最后提示出错了

start dump mysql
dump ok
start tar
tar ok
start upload
Traceback (most recent call last):
  File "./upload.py", line 48, in <module>
    qiniu.io.put_file(uptoken, os.path.basename(localfile), localfile)
  File "/root/backuptoqiniu/qiniu/io.py", line 65, in put_file
    return put(uptoken, key, f, extra)
  File "/root/backuptoqiniu/qiniu/io.py", line 54, in put
    return rpc.Client(conf.UP_HOST).call_with_multipart("/", fields, files)
  File "/root/backuptoqiniu/qiniu/rpc.py", line 59, in call_with_multipart
    return self.call_with(path, mr, content_type, mr.length())
  File "/root/backuptoqiniu/qiniu/rpc.py", line 34, in call_with
    resp = self.round_tripper("POST", path, body)
  File "/root/backuptoqiniu/qiniu/rpc.py", line 17, in round_tripper
    self._conn.request(method, path, body, self._header)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/root/backuptoqiniu/qiniu/httplib_chunk.py", line 84, in _send_request
    self.endheaders(body, is_chunked=is_chunked)
  File "/root/backuptoqiniu/qiniu/httplib_chunk.py", line 100, in endheaders
    self._send_output(message_body, is_chunked=is_chunked)
  File "/root/backuptoqiniu/qiniu/httplib_chunk.py", line 122, in _send_output
    self.send(message_body, is_chunked=is_chunked)
  File "/root/backuptoqiniu/qiniu/httplib_chunk.py", line 40, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
upload ok
backup clean done
